steps:
  # Build a docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME", "."]
  # Push the docker image to container registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME"]
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:latest"
